
# Final exercise {} 

<!-- ======================================================= -->
## Overview {  }

This page hosts training materials for the Applied Epi^TM^ “Introduction to R for Applied Epidemiology”. 
This course teaches the fundamentals of R for applied epidemiologists and public health practitioners.


<!-- ======================================================= -->
## Module {  }  

Below is a list of each of the modules included in the course. Please work your way through them systemically - in accordance with the course timetable.  
Clicking on the tutorial link will launch a new window with interactive exercises. 


::: {.tutorial}
**Module 1: Introduction to R**

We welcome you to the course and dive into the basics of how to interact with R and RStudio, basic R syntax, and how to organize your analytical projects. Finally, we cover R functions and packages, and introduce the core functions used to import data. Using these, we import the Ebola case study surveillance linelist, and begin to inspect and review it.  

- [Slides: Welcome, course logistics, RStudio, and basic R syntax](https://appliedepi.github.io/intro_course/modules/module_1/slides/course_introduction/slides_course_introduction.html)  

- Live demonstration ([instructor guide](https://appliedepi.github.io/intro_course/modules/module_1/guides/rstudio_tour.html))  

[[Tutorial]](https://aspina.shinyapps.io/basics/) [[Source]](https://github.com/appliedepi/introexercises/tree/master/inst/tutorials/basics)
:::

::: {.tutorial}
**Module 4: Data visualization with {ggplot2}**

Using the {ggplot2} package to maximum effect rests upon understanding how to apply its "grammar of graphics" to build a plot layer-by-layer. We tackle this piece-by-piece, introducing concepts one-by-one so that you build upon previous knowledge to construct informative and colorful bar plots, scatter plots, histograms, line plots, text labels that automatically update with refreshed data (very useful for epidemiological reports!), and more.  

- [Slides: Data visualization with ggplot2](https://appliedepi.github.io/intro_course/modules/module_4/slides/slides_ggplot_basics/slides_ggplot_basics.html)  

- [Slides: Scales, themes, and labels](https://appliedepi.github.io/intro_course/modules/module_4/slides/slides_ggplot_scales_labels/slides_ggplot_scales_labels.html)  
  

[[Tutorial]]( https://aspina.shinyapps.io/ggplot_basics/) [[Source]](https://github.com/appliedepi/introexercises/tree/master/inst/tutorials/ggplot_basics)
:::
